name: 'MyDynamicSecret'
on: push

jobs: 
  fetch_dynamic_secrets:
    runs-on: 'ubuntu-latest'
    name: Fetch MySQL Dynamic Secret and Update DB
    
    permissions:
      id-token: write
      contents: read
      
    steps:
    - name: Fetch MySQL Dynamic Secret from Akeyless
      id: fetch-dynamic-secrets
      uses: LanceMcCarthy/akeyless-action@v3.1.1
      with:
        access-id: ${{ secrets.ACCESS_ID }}
        dynamic-secrets: '{"mysqlDS":"MYSQL_DYNAMIC_SECRET"}'
        
    - name: Export Secret to Environment
      run: |
        echo '${{ steps.fetch-dynamic-secrets.outputs.MYSQL_DYNAMIC_SECRET }}' | jq -r 'to_entries|map("JWT_\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV
# You can now access each secret separately as environment variables
    - name: Verify Vars
      run: |
        echo "id: ${{ env.JWT_id }}"
        echo "password: ${{ env.JWT_password }}"
    
    - name: SSH into Host and Update Database Table
      run: |
        export LC_user=$${{ env.JWT_id }}
        export LC_pass=$${{ env.JWT_password }}
        echo ${{ secrets.RSA }} | base64 -d >> jeremy-demo.pem
        chmod 600 jeremy-demo.pem
        scp -o StrictHostKeyChecking=no -i "jeremy-demo.pem" employee.sh ubuntu@3.133.90.136:~/.
        ssh -o "SendEnv LC_*" -o StrictHostKeyChecking=no -i "jeremy-demo.pem" ubuntu@3.133.90.136 -t "bash employee.sh" # SSH into Remote EC2 Host and update DB
        echo "Database Employees updated!"
