name: 'Fetch Static and Dynamic Secrets to Update MySQL DB'
on: push

jobs:
  fetch_static_dynamic_secrets:
    runs-on: 'ubuntu-latest'
    name: Use MySQL Dynamic Secret to Update DB
    
    permissions:
      id-token: write
      contents: read
      
    steps:
    - name: Fetch Private Key Static Secret and MySQL Dynamic Secret from Akeyless
      id: fetch-secrets
      uses: LanceMcCarthy/akeyless-action@v3.1.1
      with:
        access-id: ${{ secrets.ACCESS_ID }}
        static-secrets: '{"jeremy-demo":"MY_RSA"}'
        dynamic-secrets: '{"mysqlDS":"MYSQL_DYNAMIC_SECRET"}'
        
    - name: Create PEM File & Export Dynamic Secret to Environment
      run: |
        echo ${{ env.MY_RSA }} | base64 -d >> jeremy-demo.pem      
        echo '${{ steps.fetch-secrets.outputs.MYSQL_DYNAMIC_SECRET }}' | jq -r 'to_entries|map("JWT_\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV

    - name: Verify Vars
      run: |
        echo "id: ${{ env.JWT_id }}"
        echo "password: ${{ env.JWT_password }}"
        
    - name: SSH into Host and Update Database Table
      run: |
        echo -e '#!/bin/bash' >> employee.sh
        echo -e "mysql -u\$LC_user -p\$LC_pass -e 'USE Employees; INSERT INTO employees (First_Name,Last_Name) VALUES (\"Gwen\",\"Stacy\");'" >> employee.sh
        export LC_user=${{ env.JWT_id }}
        export LC_pass=${{ env.JWT_password }}
        chmod 600 jeremy-demo.pem
        scp -o StrictHostKeyChecking=no -i "jeremy-demo.pem" employee.sh ubuntu@18.216.59.37:~/.
        ssh -o "SendEnv LC_*" -o StrictHostKeyChecking=no -i "jeremy-demo.pem" ubuntu@18.216.59.37 -t "bash employee.sh" # SSH into Remote EC2 Host and update DB
        echo "Database Employees updated!"
